"""empty message

Revision ID: cdcd89b3d017
Revises: 
Create Date: 2017-09-28 14:55:45.516344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdcd89b3d017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.create_index(op.f('ix_cluster_clade_enrichment_clade_id'), 'cluster_clade_enrichment', ['clade_id'], unique=False)
    op.create_index(op.f('ix_cluster_clade_enrichment_cluster_id'), 'cluster_clade_enrichment', ['cluster_id'], unique=False)
    op.create_foreign_key(None, 'cluster_clade_enrichment', 'clades', ['clade_id'], ['id'])
    op.create_foreign_key(None, 'cluster_clade_enrichment', 'coexpression_clusters', ['cluster_id'], ['id'])
    op.alter_column('conditions_tissue', 'in_tree',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('expression_network_methods', 'enable_second_level',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('expression_network_methods', 'hrr_cutoff',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'30'"))
    op.alter_column('expression_network_methods', 'pcc_cutoff',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'-2'"))
    op.create_index(op.f('ix_family_go_gene_family_id'), 'family_go', ['gene_family_id'], unique=False)
    op.create_index(op.f('ix_family_go_go_id'), 'family_go', ['go_id'], unique=False)
    op.create_foreign_key(None, 'family_go', 'go', ['go_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'family_go', 'gene_families', ['gene_family_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_family_interpro_gene_family_id'), 'family_interpro', ['gene_family_id'], unique=False)
    op.create_index(op.f('ix_family_interpro_interpro_id'), 'family_interpro', ['interpro_id'], unique=False)
    op.create_foreign_key(None, 'family_interpro', 'interpro', ['interpro_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'family_interpro', 'gene_families', ['gene_family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'family_interpro', type_='foreignkey')
    op.drop_constraint(None, 'family_interpro', type_='foreignkey')
    op.drop_index(op.f('ix_family_interpro_interpro_id'), table_name='family_interpro')
    op.drop_index(op.f('ix_family_interpro_gene_family_id'), table_name='family_interpro')
    op.drop_constraint(None, 'family_go', type_='foreignkey')
    op.drop_constraint(None, 'family_go', type_='foreignkey')
    op.drop_index(op.f('ix_family_go_go_id'), table_name='family_go')
    op.drop_index(op.f('ix_family_go_gene_family_id'), table_name='family_go')
    op.alter_column('expression_network_methods', 'pcc_cutoff',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'-2'"))
    op.alter_column('expression_network_methods', 'hrr_cutoff',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'30'"))
    op.alter_column('expression_network_methods', 'enable_second_level',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conditions_tissue', 'in_tree',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'cluster_clade_enrichment', type_='foreignkey')
    op.drop_constraint(None, 'cluster_clade_enrichment', type_='foreignkey')
    op.drop_index(op.f('ix_cluster_clade_enrichment_cluster_id'), table_name='cluster_clade_enrichment')
    op.drop_index(op.f('ix_cluster_clade_enrichment_clade_id'), table_name='cluster_clade_enrichment')
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(collation='latin1_general_ci', length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(collation='latin1_general_ci'), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
